cannon_shot : cannon_shot.cpp glad.c
				g++ -o cannon_shot cannon_shot.cpp glad.c -lGL -lglfw -lftgl -lSOIL -ldl -I/usr/local/include -I/usr/local/include/freetype2 -L/usr/local/lib

clean:
		rm cannon_shot				